development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:5b753cce22d0740513d1cc96005a6b10@soldierfish.redistogo.com:10161/
  channel_prefix: Hang_production
